services:
  battleborn-customer-support-ai:
    build: .
    container_name: battleborn-customer-support-ai
    environment:
      - NVIDIA_API_KEY=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
      - CLOUD_MODEL=nvidia/nemotron-3-nano-30b-a3b
      - KB_PATH=data/knowledge_base.json
    stdin_open: true
    ports:
      - "5000:5000"
    tty: true
    networks:
      - agents-net

networks:
  agents-net:
    external: true
