services:
  battleborn-customer-support-ai:
    build: .
    container_name: battleborn-customer-support-ai
    environment:
      - OPENAI_API_KEY=your-openai-api-key-here
      - CLOUD_MODEL=gpt-4.1-mini
      - KB_PATH=data/knowledge_base.json
    stdin_open: true
    ports:
      - "5000:5000"
    tty: true
    networks:
      - agents-net

networks:
  agents-net:
    external: true

